---
name: Pipeline IaC

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    timeout-minutes: 15
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2