---
name: Pipeline IaC

on:
  push:
    branches:
      - main

jobs:
  terraform:
    timeout-minutes: 15
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.3

    - name: Terraform Init
      run: terraform init
    - name: Terraform Apply
      run: terraform apply -input=false -compact-warnings -var-file=develop.auto.tfvars -auto-approve
      